// Every element grabbed once here instead of scattering document.getElementById calls
// throughout the codebase, so every other module reads the DOM through this one file.
export const els = {
  minRating: document.getElementById('minRating'),
  minRatingVal: document.getElementById('minRatingVal'),
  minVotes: document.getElementById('minVotes'),
  englishOnly: document.getElementById('englishOnly'),
  includePartialEnglish: document.getElementById('includePartialEnglish'),
  includeMTL: document.getElementById('includeMTL'),
  originalJapaneseOnly: document.getElementById('originalJapaneseOnly'),
  yearFrom: document.getElementById('yearFrom'),
  yearTo: document.getElementById('yearTo'),
  lengthGrid: document.getElementById('lengthGrid'),
  includeInput: document.getElementById('includeInput'),
  includeSuggest: document.getElementById('includeSuggest'),
  includeStatus: document.getElementById('includeStatus'),
  includeChips: document.getElementById('includeChips'),
  excludeInput: document.getElementById('excludeInput'),
  excludeSuggest: document.getElementById('excludeSuggest'),
  excludeStatus: document.getElementById('excludeStatus'),
  excludeChips: document.getElementById('excludeChips'),
  listSize: document.getElementById('listSize'),
  generateBtn: document.getElementById('generateBtn'),
  resetBtn: document.getElementById('resetBtn'),
  statusLine: document.getElementById('statusLine'),
  activeFilters: document.getElementById('activeFilters'),
  prevBtn: document.getElementById('prevBtn'),
  nextBtn: document.getElementById('nextBtn'),
  counter: document.getElementById('counter'),
  card: document.getElementById('card'),
  cover: document.getElementById('cover'),
  coverLink: document.getElementById('coverLink'),
  coverFallback: document.getElementById('coverFallback'),
  coverLoading: document.getElementById('coverLoading'),
  revealBtn: document.getElementById('revealBtn'),
  statStrip: document.getElementById('statStrip'),
  titleMain: document.getElementById('titleMain'),
  titleAlt: document.getElementById('titleAlt'),
  tagRow: document.getElementById('tagRow'),
  dialogue: document.getElementById('dialogue'),
  vndbLink: document.getElementById('vndbLink'),
  includeModeToggle: document.getElementById('includeModeToggle'),
  excludeModeToggle: document.getElementById('excludeModeToggle')
};
